create table public.notes (id bigint generated by default as identity primary key,name text not null check (char_length(name) between 1 and 60),message text not null check (char_length(message) between 1 and 1000),created_at timestamptz not null default now());
alter table public.notes enable row level security;
drop policy if exists "Anyone can read notes" on public.notes;
create policy "Anyone can post notes" on public.notes for insert to anon with check (true);
